# Generated by Django 2.2.4 on 2021-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20210714_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
